# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Intersectional Business Academy
email: anna@learneq.ca
description: > # this means to ignore newlines until "baseurl:"
  The Intersectional Business Academy is a space for entrepreneurs to learn
  about the intersection of business and social justice, and how to apply these
  principles in their work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "assets/img/logos/FB Avatar.png"
twitter_username: 
github_username: 

# Copyright time
time: 2024-01-01

# Company Information
company_name: The Intersectional Business Academy
address_line: Toronto, Ontario
telephone_number: 1.800.245.356
fax_number: 1.800.245.357
company_email: info@learneq.ca
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d721.0469277889509!2d-79.39868673028954!3d43.70664796766089!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882b333cbc996b59%3A0xedee9cf62c8978ce!2s1%20Eglinton%20Ave%20E%20Level%20C-400%2C%20Toronto%2C%20ON%20M4P%201A1!5e0!3m2!1sen!2sca!4v1755312211732!5m2!1sen!2sca

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-font-awesome-sass

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
